dist: xenial

language: cpp
compiler: g++

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-8
            - cmake
script:
    # https://stackoverflow.com/a/41916657
    # Link gcc-8 and g++-8 to their standard commands
    - ln -s /usr/bin/gcc-8 /usr/local/bin/gcc
    - ln -s /usr/bin/g++-8 /usr/local/bin/g++
    # Export CC and CXX to tell cmake which compiler to use
    - export CC=/usr/bin/gcc-8
    - export CXX=/usr/bin/g++-8
    # Check versions of gcc, g++ and cmake
    - gcc -v && g++ -v && cmake --version
    # Have to disable some features to get travis to build,
    # in particular must switch to 64-bit mode.
    - cmake . -DRELEASE=ON -DNETWORKING=OFF -DX64=ON
    - make
    - ./ogm-test
