# TODO: fcl dependency needs to be fixed.

version: '1.0.{build}'

image: 
  - Visual Studio 2017

platform:
  - x86
 
configuration:
  - Debug
  
cache:
  - C:\Tools\vcpkg\

install:
# check that these tools exist
  - SET PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - python --version
# we need this later
  - powershell -Command "Invoke-WebRequest -OutFile Dependencies.zip https://github.com/lucasg/Dependencies/releases/download/v1.10/Dependencies_x86_Release.zip"
  - 7z e Dependencies.zip
  - Dependencies.exe
# future-proofing
  - git submodule update --init --recursive
# dependencies
  - vcpkg install sdl2:x86-windows sdl2-image:x86-windows sdl2-mixer:x86-windows sdl2-ttf:x86-windows
  - vcpkg install readline:x86-windows
  # - vcpkg install assimp:x86-windows fcl:x86-windows boost-filesystem:x86-windows
  - vcpkg install glew:x86-windows glm:x86-windows
# for debugging purposes
  - dir C:\Tools\vcpkg\*.dll /a-D /S /B

before_build:
  - cmake -DRELEASE=ON -DNO_FCL=ON -DVCPKG_TARGET_TRIPLET=x86-windows -DCMAKE_TOOLCHAIN_FILE=C:\Tools\vcpkg\scripts\buildsystems\vcpkg.cmake -A Win32 .

build:
  project: $(APPVEYOR_BUILD_FOLDER)\ogm-test.vcxproj

after_build:
  - "SET PATH=C:\\Python34;C:\\Python34\\Scripts;%PATH%"
  - python assemble-release.py "%APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%"
  - 7z a ogm-win32.zip ogm_release/

test_script:
  - SET PATH=%PATH%;C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin
  #- dumpbin /dependents %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\ogm.exe
  #- dumpbin /dependents %APPVEYOR_BUILD_FOLDER%\%CONFIGURATION%\ogm-test.exe
  #- Dependencies.exe -chain -imports ogm_release/ogm-test.exe
  #- Dependencies.exe -imports ogm_release/ogm.exe
  #- ogm_release/ogm-test.exe
  #- ogm_release/ogm.exe --help
  
artifacts:
  - path: ogm-win32.zip
  - path: '**\*.exe'
  - path: '**\*.dll'
